#######
##Event Creation and Signal Object Generation for Each subject:

#Overall strcture: 
  #Get to dir, loop over each subject use ID
  #Single sub data proc: use post VBA results and b
  #Assign them to environment as each ID as an list object that contains Event and Signal object which are compatible with pipeline

#Objectives:
  #Read .mat files and see if we need to restructure that

#Compare performance between readMat and read.mat

#Let's make sense of the process:
  #1, time bin size; calculated by frequency scaling 
  #2, bandit design matrix? Change and modify it

#This function is used to index the mat file generated by r.matlab; 
#Reconstruction functions:
#Maybe you can try using recon method designated for list or array;
#Following will 
recon.list<-function(mat.raw=NULL){
  mat.better<-sapply(mat.raw, function(x){
    emp<-list()
    drop(x)->x
    for (i in 1:length(x)) {
      rownames(x)[i]->whichone
      emp[[whichone]]<-drop(x[i])
    }
    return(emp)
  })
  names(mat.better)<-names(mat.raw)
  return(mat.better)
}
recon.array<-function(x=NULL) {
  emp<-list()
  for (i in 1:length(x)) {
    rownames(x)[i]->whichone
    if (length(emp[[whichone]][[1]])==1) {
      emp[[whichone]]<-drop(unlist((x[[i]])))
    } else if (ifelse(is.null(dim(x[[i]])[1]),-1,dim(x[[i]])[1]) == 1) {
      emp[[whichone]]<-drop(unlist(x[[i]]))
    } else {emp[[whichone]]<-drop((x[[i]]))}
  }
#names(emp)<-names(x)
return(emp)
}

#TO DO: Try to make recursive
recon.mat<-function(data.raw=NULL) {
  #do recurisive if class of x is list, if it's array then use 
  if (class(data.raw)=="list") {
    lapply(data.raw, function(x) {
      
    }) 
  } else if (class(data.raw)=="array") {
    data.raw<-recon.array(x=data.raw)
  } else if (!lapply(huy$muX,class) %in% c("list","array")) {}
    
  }


makeeprimestruct<-function(rawtext=file.choose(),
                           rawdf=NULL,
                           breakpointname="BreakProc") {
  if (is.null(rawdf)){
    rawdf<-read.csv(rawtext,stringsAsFactors = F,sep = "\t")
  } 
  wherearethebreaks<-grep(breakpointname,rawdf$Procedure)
  rawdf$blocknum<-NA

  for (i in 1:(length(wherearethebreaks)+1)) {
    print(i)
    if (i==1) {
      rawdf$blocknum[i:wherearethebreaks[i]]<-i
      
    } else if (i==(length(wherearethebreaks)+1)) {
      rawdf$blocknum[wherearethebreaks[i-1]:length(rawdf$Procedure)]<-i
     
    } else {
      rawdf$blocknum[wherearethebreaks[i-1]:wherearethebreaks[i]]<-i}
  }
  df<-rawdf[-wherearethebreaks,]
  df$trailnum<-seq_along(df$Procedure)
  df$trialnum.block<-unsplit(lapply(split(df$blocknum,df$blocknum), seq_along),df$blocknum)
  return(df)
}

sigmatransform<-function(x) {
  (1./(1+exp(x)))->y
  return(y)
}

depthoflist <- function(list,thisdepth=0){
  if(!is.list(list)){
    return(thisdepth)
  }else{
    return(max(unlist(lapply(list,depthoflist,thisdepth=thisdepth+1))))    
  }
}

addcenterscaletolist<-function(list) {
  test<-lapply(list, scale,center=T)
  names(test)<-paste(names(list),"centerscaled",sep = "_")
  newlist<-c(list,test) 
  return(newlist)
}

#End

#bandit specific functions:


#Make single signal as a list:
makesignal.single<-function(output,ename,norm="none",normargu=c("durmax_1","evtmax_1"),valuefrom,modifier=NA,style="subset",nonah=T) {
  jrz<-list()
  jrz[["event"]]<-ename
  jrz[["normalization"]]<-norm
  jrz[normargu]<-TRUE
  
  subelist<-output$event.list$allconcat[which(output$event.list$allconcat$event==ename),]
  value<-output$value[[valuefrom]]
  
  value.df<-data.frame(
    run=subelist$run,
    trial=subelist$trial,
    value=value
  )
  if (!is.na(modifier)) {
    #INVERTING THE LOGICAL STATEMENT SO 1 for valid trials and 0 for non-valid!
    if (nonah) {
    modx<-!output$output.df[modifier] & !is.na(subelist$onset)
    } else { modx<-!output$output.df[modifier]}
    switch (style,
            "multiply" = {value.df$value<-value.df$value * as.numeric(modx)},
            "subset"   = {value.df<-value.df[modx ,]}
    )
    
  }
  jrz[["value"]]<-value.df
  return(jrz)
}

#Make all of them with a grid:
makesignalwithgrid<-function(dsgrid=read.csv("grid.csv",stringsAsFactors = FALSE), outputdata=NULL,nona=F, expectedtn=300,add_taskness=F) {
  if (is.null(outputdata)) {stop("NO DATA")}
  allofthem<-new.env(parent = emptyenv())
  dsgrid[dsgrid=="NA"]<-NA
  for (i in 1:length(dsgrid$ename)) {
    print(paste("making...",dsgrid$valuefrom[i],sep=""))
    #could have totally do a do.call and make assignment within single function 
    #but that ONE datainput variable is hard to get by with do.call so......loop is fine
    #Forcing all arguments so it's kinda bad....
    result<-makesignal.single(output = outputdata,
                              ename = dsgrid$ename[i],
                              norm = dsgrid$norm[i],
                              normargu = dsgrid$normargu[i],
                              valuefrom = dsgrid$valuefrom[i],
                              modifier = dsgrid$modifier[i],
                              style = dsgrid$style[i],
                              nonah = nona)
    assign(dsgrid$name[i],result,envir = allofthem)
  }
  
  #change it to list:
  allofthemlist<-as.list(allofthem)
  
  #Taskness varibale:
  if (add_taskness) {
  for (taskname in unique(dsgrid$ename)) {
    
    if (any(is.na(output$event.list[[taskname]]))) {
      tempdf<-output$event.list[[taskname]][which(!is.na(output$event.list[[taskname]]$onset)),]
      tempdf.a<-subset.data.frame(tempdf,select = c("run","trial"))
      tempdf.a$value<-1
      allofthemlist[[paste(taskname,"_evt",sep = "")]] <- list(value=tempdf.a,event=taskname,normalization="none")
    }else {allofthemlist[[paste(taskname,"_evt",sep = "")]] <- list(value=1,event=taskname,normalization="none")}
  }
}
  return(allofthemlist)
  
}

getnuisancefrompipe<-function(id=NULL,
                              cfgfilepath="/Volumes/bek/autopreprocessing_pipeline/bandit_oldPreCMMR.cfg"
) {
  cfg<-readLines(cfgfilepath,n=grep("export",readLines(cfgfilepath))[1]-1)
}





#Use data.frame"
 #Name, Begining, Ending, alter = name, beg, dura

#directory to nuisances
# 
# con <- dbConnect(odbc(),
#                  Driver = "SQLServer",
#                  Server = "OACDATA4",
#                  Database = "crc",
#                  UID = "chenj20",
#                  PWD = rstudioapi::askForPassword("Database password"),
#                  Port = 1433)









