#######
##Event Creation and Signal Object Generation for Each subject:

#Overall strcture: 
  #Get to dir, loop over each subject use ID
  #Single sub data proc: use post VBA results and b
  #Assign them to environment as each ID as an list object that contains Event and Signal object which are compatible with pipeline

#Objectives:
  #Read .mat files and see if we need to restructure that

#Compare performance between readMat and read.mat
start_time <- Sys.time()
R.matlab::readMat(filena)->testmat #doesn't even work
#rmatio::read.mat(filena)->testmat.2 #Use #C which is way more efficient, although it seems like it comes with error message 
end_time <- Sys.time()







#make a configuration file so organizer knows what to grab

#Let's make sense of the process:
  #1, time bin size; calculated by frequency scaling 
  #2, bandit design matrix? Change and modify it

#This function is used to index the mat file generated by r.matlab; 
recon.mat<-function(mat.raw=NULL){
  mat.better<-sapply(mat.raw, function(x){
    emp<-list()
    for (i in 1:length(x)) {
      rownames(x)[i]->whichone
      emp[[whichone]]<-unlist(x[i])
    }
    return(emp)
  })
  names(mat.better)<-names(mat.raw)
  return(mat.better)
}

recon.within<-function(data=NULL) {
  emp<-list()
  for (i in 1:length(x)) {
    rownames(x)[i]->whichone
    emp[[whichone]]<-unlist(x[i])
  }
  return(emp)
  names(emp)<-names(data)
  return(emp)
}
  
dnpl.makeeprimestruct<-function(rawtext=file.choose(),
                           rawdf=NULL,
                           breakpointname="BreakProc") {
  if (is.null(rawdf)){
    rawdf<-read.csv(rawtext,stringsAsFactors = F,sep = "\t")
  } 
  wherearethebreaks<-grep(breakpointname,rawdf$Procedure)
  rawdf$blocknum<-NA

  for (i in 1:(length(wherearethebreaks)+1)) {
    print(i)
    if (i==1) {
      rawdf$blocknum[i:wherearethebreaks[i]]<-i
      
    } else if (i==(length(wherearethebreaks)+1)) {
      rawdf$blocknum[wherearethebreaks[i-1]:length(rawdf$Procedure)]<-i
     
    } else {
      rawdf$blocknum[wherearethebreaks[i-1]:wherearethebreaks[i]]<-i}
  }
  df<-rawdf[-wherearethebreaks,]
  df$trailnum<-seq_along(df$Procedure)
  df$trialnum.block<-unsplit(lapply(split(df$blocknum,df$blocknum), seq_along),df$blocknum)
  return(df)
}


ds.bandit<-list(nblock=3, ntrial=300, names.event=c("decision","feedback","trial"),
                duration_feedback.mm=1000)

bandit.proc<-function(data.mat=data.mat,design=ds.bandit,ifkind=c("myst","comp")){
  if (is.null(data.mat)) {stop("NO INPUT")}
  ###########do df structure
  
  #NOTE: ALL THE LOGICAL VARIABLES ARE FALSE FOR ABSENT / TRUE FOR EXIST; 
  
  #C0: Create empty environment to put stuff in so that they don't just float around function space but rather saved
  #Also it'd be easier to grab them in later function or loop; since environments are on search path
  #Also, with the envir2df function, it can be converted to df with identical length! #bsrc::dnpl.envir2df(wking)
  wking<-new.env(parent = emptyenv())
  
  #C1: get myst and comp trials
  checkzx<-lapply(ifkind, function(x) {
    logiccheck<-!as.logical(seq_along(data.mat$b$protocol.type))
    logiccheck[grep(x,data.mat$b$protocol.type)]<-TRUE
    logiccheck
  })
  names(checkzx)<-ifkind
  #End 
  
  #C2: Make Choice and feedback sensor
  assign("zerort_logical", {as.logical(unlist(data.mat$b$stim.RT)=="0" | unlist(data.mat$b$chosen.stim)=="999")},
         envir = wking)
  assign("choice_logical", {as.logical(zerort.logical | checkzx$comp)}, envir = wking)
  assign("feedback_logical", {as.logical(zerort.logical | checkzx$myst)}, envir = wking)
  #END 
  
  #C3: Make trial number & block number timing variables:
  blocknum<-rep(1:ds.bandit$nblock,each=(ds.bandit$ntrial / ds.bandit$nblock))
  assign("run",blocknum,envir = wking)
  assign("trialbyblock",unsplit(lapply(split(blocknum,blocknum), seq_along),blocknum),envir = wking)
  glmm<-lapply(split(seq(1:ds.bandit$ntrial),blocknum), function(x) {
      xrange<-min(x):max(x)
      #time<-data.mat$b$stim.OnsetTime
      return(list(decision_onset=data.mat$b$stim.OnsetTime[xrange]-data.mat$b$stim.OnsetTime[min(x)],
                  decision_end=data.mat$b$stim.OnsetTime[xrange]-data.mat$b$stim.OnsetTime[min(x)]+data.mat$b$stim.RT[xrange],
                  feedback_onset=data.mat$b$feedback.OnsetTime[xrange]-data.mat$b$feedback.OnsetTime[min(x)],
                  feedback_end=data.mat$b$feedback.OnsetTime[xrange]-data.mat$b$feedback.OnsetTime[min(x)]+ds.bandit$duration_feedback.mm,
                  trial_onset=data.mat$b$stim.OnsetTime[xrange]-data.mat$b$stim.OnsetTime[min(x)],
                  trial_end=data.mat$b$stim.OffsetTime[xrange]-data.mat$b$stim.OffsetTime[min(x)]
                  ))
  })

  tes.en<-new.env(parent = emptyenv())
  assign("lzy",list(),envir = tes.en)
  tes<-lapply(glmm, function(x) {
      # assign("tempx",x,envir = tes.en)
      # lapply(names(x),function(y){
      #   xz<-get("tempx",envir = tes.en)
      #   
      # })
    get("lzy",envir = tes.en)->lzy
    for (y in names(x)) {
      lzy[[y]]<-c(lzy[[y]],x[[y]])
    }
    assign("lzy",lzy,envir = tes.en)
    })
  get("lzy",envir = tes.en)->lzy
  for (i in names(lzy)) {
    assign(i,lzy[[i]],envir = wking)
  }
  
  #Last step, get all the ones from 
  finalist<-list()
  for (nev in names.event) { #Loop around 
    objects(envir = wking)[grep(nev,objects(envir = wking))]->whichones
    finalist[[nev]]<-data.frame(
      eventname=nev,
      onset=get(whichones[grep("onset",whichones)],envir = wking),
      duration=get(whichones[grep("end",whichones)],envir = wking) - get(whichones[grep("onset",whichones)],envir = wking),
      run=wking$run,
      trial=wking$trialbyblock
    )
  }
  
  for (i in 1:length(finalist)) {
    if (i==1) {ktz<-finalist[[i]]} else {
    ktz<-rbind(ktz,finalist[[i]])}
  }
  finalist[["allconcat"]]<-ktz
  vba<-recon.mat(data.mat$out$suffStat)
  output<-list(event.list=finalist,output.df=bsrc::dnpl.envir2df(wking),vba=vba)
  return(output)
}





#Use data.frame"
 #Name, Begining, Ending, alter = name, beg, dura

#directory to nuisances











